/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Imam Dwi Cahyo
 * Kelas IF-11
 * NIM 10116494
 */
public class ViewAplikasiPendataan extends javax.swing.JFrame {

    /**
     * Creates new form ViewAplikasiPendataan
     */
    public ViewAplikasiPendataan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jJudul1 = new javax.swing.JLabel();
        jNama = new javax.swing.JLabel();
        jKelamin = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        jJurusan = new javax.swing.JLabel();
        comboboxJurusan = new javax.swing.JComboBox<>();
        checkboxProgramming = new javax.swing.JCheckBox();
        jMinat = new javax.swing.JLabel();
        checkboxDesignUIUX = new javax.swing.JCheckBox();
        checkboxGame = new javax.swing.JCheckBox();
        jAreaPenempatan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAreaPenempatan = new javax.swing.JList<>();
        jOutput = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputHasil = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jJudul1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jJudul1.setText("APLIKASI PENDATAAN VOLUNTER DEV SUMMIT");

        jNama.setText("Nama");

        jKelamin.setText("Jenis Kelamin");

        InputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNamaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMale);
        radioMale.setText("Male");

        buttonGroup1.add(radioFemale);
        radioFemale.setText("Female");

        jJurusan.setText("Jurusan");

        comboboxJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEKNIK INFORMATIKA", "AKUTANSI", "SISTEM INFORMASI", "TEKNIK KOMPUTER", "BAHASA INGGRIS", "DESAIN KOMUNIKASI VISUAL" }));

        checkboxProgramming.setText("Programming");

        jMinat.setText("Minat");

        checkboxDesignUIUX.setText("Design UI UX");

        checkboxGame.setText("Game");
        checkboxGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxGameActionPerformed(evt);
            }
        });

        jAreaPenempatan.setText("Area Penempatan");

        listAreaPenempatan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "DEV SUMMIT BANDUNG", "DEV SUMMIT JAKARTA", "DEV SUMMIT SURABAYA", "DEV SUMMIT YOGYAKARTA" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listAreaPenempatan.setToolTipText("");
        listAreaPenempatan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(listAreaPenempatan);

        jOutput.setText("Output");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        outputHasil.setBackground(new java.awt.Color(200, 200, 200));
        outputHasil.setColumns(20);
        outputHasil.setRows(5);
        jScrollPane3.setViewportView(outputHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNama)
                    .addComponent(jKelamin)
                    .addComponent(jJurusan)
                    .addComponent(jMinat)
                    .addComponent(jAreaPenempatan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jJudul1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radioFemale)
                            .addComponent(radioMale)
                            .addComponent(checkboxGame)
                            .addComponent(checkboxDesignUIUX)
                            .addComponent(checkboxProgramming)
                            .addComponent(jScrollPane1)
                            .addComponent(comboboxJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputNama)
                            .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOutput)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jJudul1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNama)
                    .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jKelamin)
                            .addComponent(radioMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jJurusan)
                            .addComponent(comboboxJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkboxProgramming)
                            .addComponent(jMinat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxDesignUIUX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAreaPenempatan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSimpan))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        String jenisKelamin = " ";
        
        if (radioMale.isSelected()){
            jenisKelamin = "Male";
        }else{
            jenisKelamin = "Female";
        }
        
        String jurusan = comboboxJurusan.getSelectedItem().toString();
            
        String minat = " ";
        int isi = 0;
        if (checkboxProgramming.isSelected()){
            minat = minat +"-Programming";
            isi = isi + 1;
        }
        if (checkboxDesignUIUX.isSelected()){
            if (isi > 0){
                minat = minat +"\n\t   -Desain UI UX";
            }else{
                minat = minat +"-Desain UI UX";
            }
            isi = isi + 1;
        }
        if (checkboxGame.isSelected()){
            if (isi > 0){
            minat = minat +"\n\t   -Game";
            }else{
                minat = minat +"-Game";
            }
        }
        
        String penempatan;
        penempatan = listAreaPenempatan.getSelectedValue().toString();
        
        outputHasil.setText
        (
            "Nama\t: "+InputNama.getText()+
            "\nJenis Kelamin\t: "+jenisKelamin+
            "\nJurusan\t: "+jurusan+
            "\nMinat\t: "+minat+
            "\nPenempatan\t: "+penempatan
        );
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void InputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNamaActionPerformed

    private void checkboxGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAplikasiPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAplikasiPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAplikasiPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAplikasiPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAplikasiPendataan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputNama;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JCheckBox checkboxDesignUIUX;
    private javax.swing.JCheckBox checkboxGame;
    private javax.swing.JCheckBox checkboxProgramming;
    private javax.swing.JComboBox<String> comboboxJurusan;
    private javax.swing.JLabel jAreaPenempatan;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJurusan;
    private javax.swing.JLabel jKelamin;
    private javax.swing.JLabel jMinat;
    private javax.swing.JLabel jNama;
    private javax.swing.JLabel jOutput;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listAreaPenempatan;
    private javax.swing.JTextArea outputHasil;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    // End of variables declaration//GEN-END:variables
}
